#! /bin/sh

exec /home/ken/.loginrc/beastie-start.sh &

sxhkd -c /usr/home/ken/.config/sxhkd/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	0
bspc config window_gap          	16
bspc config focus_follows_pointer 	true
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
